# Generated by Django 5.0 on 2025-08-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pimg', models.ImageField(default='img/water.jpg', upload_to='img/')),
            ],
        ),
    ]
