# Generated by Django 5.0 on 2025-08-20 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], max_length=1, unique=True)),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'staff'}, related_name='staff_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
