# Generated by Django 5.0 on 2025-08-27 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role_staffgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga', models.CharField(choices=[('Kumbotso', 'Kumbotso'), ('Tudun Wada', 'Tudun Wada'), ('Dambatta', 'Dambatta'), ('Kiru', 'Kiru')], default='kumbotso', max_length=50)),
                ('driver', models.OneToOneField(default=None, limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
