# Generated by Django 5.0 on 2025-08-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_driverroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverRoute',
        ),
    ]
