# Generated by Django 5.0 on 2025-08-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
