# Generated by Django 5.0 on 2025-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_driver_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lga',
            field=models.CharField(default='kumbotso', max_length=50),
        ),
    ]
