# Generated by Django 5.0 on 2025-08-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lga',
            field=models.CharField(choices=[('tudun', 'Tudun Wada'), ('kumbotso', 'Kumbotso'), ('dambatta', 'Danbatta'), ('kiru', 'Kiru')], default='kumbotso', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Processing'), ('delivering', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
